name: souschef
description: An App to help identify recipes from pictures of ingredients or food.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.5+3
  http: ^1.1.0
  url_launcher: ^6.3.1
  english_words: ^4.0.0
  provider: ^6.0.0
  dotenv: ^4.2.0
  sqflite: ^2.0.1
  sqflite_common_ffi: any
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env


